### ISSUE TITLE
Making the picture directly zoomable when page is changed

### ISSUE THREAD

**Issue by msw333** [fireslime/photo_view#133]
Comparing PhotoViewGallery.builder to native functionality, like e.g. within iOS, I find that the overall experience is different:

1. Since scrolling between pages blocks zooming, I suggest, that the speed of transition speeds up (especially at the end). Any easy solution to do that? Otherwise, many users try zooming (which is blocked, even though the page appears to be already snapped in).

2. Is there a way to block changing pages when two fingers are on the picture, so that zooming is the primary gesture?

3. iOS allows you to change pages, even tough you are zoomed in (with a nice bouncing effect).

Thanks a lot - it's a great package.

**Comment by renancaraujo** [comment]
We had lots of pf changes on the Gallery recently (#197). I believe your point 2 is now resolved.
Regarding blocking page change when zooming in, that was changed on #197 as well. 

But we still have the problem regarding page change speed and I think the page change effect could be better. We can improve that in the future.

**Comment by renancaraujo** [comment]
Since we got no answer for a while, I am automatically closing this issue for the sake of organization.
  If there is any news on that, feel free to retake the discussion.
