### ISSUE TITLE
[BUG] PhotoView Gallery Bug on Dynamically Changing Scroll Direction

### ISSUE THREAD

**Issue by sasalx** [fireslime/photo_view#183]
**Describe the bug**
While building `PhotoViewGallery` with static `scrollDirection` works fine but I want to give the ability of changing it while **in** in `PhotoViewGallery` via a state called `readingMode`.  A simple example would be: 
`scrollDirection: readingMode ? Axis.vertical : Axis.horizontal`. This however causes a bug where the half of an image counts as one. Slider itself also malfunctions.

**To Reproduce**
1- Create a StatefulWidget.
2- Add a state to change `scrollDirection`.
3- In build create an example `PhotoViewGallery`.
3- With the help of a button or something similar change the state you created while in the `PhotoViewGallery.`

**What is the current behavior?**
Index counts half of the image as one and as a result you can only swipe half on an image.
 
**Expected behavior**
It should slide per image.

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
- Flutter: 1.9.1+hotfix.4
- Photo View: 0.5.0
- OS: Both on Android 9 and IOS 12

**Comment by renancaraujo** [comment]
@sasalx Is it possibly related to https://github.com/flutter/flutter/issues/16481

**Comment by sasalx** [comment]
Hello @renancaraujo , I think it's the same problem yes. I also opened [my own issue](https://github.com/flutter/flutter/issues/43380) related to the same problem. From the looks of it, it's an index calculation problem.

**Comment by renancaraujo** [comment]
Looksmlike it was fixed on https://github.com/flutter/flutter/pull/61973
