### ISSUE TITLE
[BUG]when using CachedNetworkImage Provider as the imageprovider, the ImageChunkEvent of loadingBuilder has always been null

### ISSUE THREAD

**Issue by 252162875** [fireslime/photo_view#278]
It is normal when I use NetworkImage as the imageprovider, but when using CachedNetworkImage Provider as the imageprovider, the ImageChunkEvent of loadingBuilder has always been null
![image](https://user-images.githubusercontent.com/18607783/80669016-edc50280-8ad5-11ea-983e-06900a91f18c.png)
![image](https://user-images.githubusercontent.com/18607783/80669081-1d740a80-8ad6-11ea-8b6f-dd969d1f1cf3.png)

**Comment by janiokq** [comment]
use flutter  1.17   Is there a solution to the same problem
