### ISSUE TITLE
[BUG] After setState() PhotoViewGallery will flash.

### ISSUE THREAD

**Issue by Aoi-hosizora** [fireslime/photo_view#292]
**Versions**
Flutter: 1.19.0-2.0.pre.83
Android 8
photo_view: ^0.9.2

**Describe the bug**

I used `PhotoViewGallery.builder` to display a list of image, and I also have some actions and need to `setState()` to update UI. But whenever I invoke `setState()`, `PhotoViewGallery` will flash at a moment.

I think it reloads the image after `setState` so it flashes. When the image is larger, this duration is long.
So how could I force not to reload the image? Or just keepalive?

**To Reproduce**

Here is my code:

```dart
Container(
  decoration: BoxDecoration(color: Colors.black),
  constraints: BoxConstraints.expand(
    height: MediaQuery.of(context).size.height,
  ),
  child: Stack(
    children: [
      Positioned.fill(
        child: PhotoViewGallery.builder(
          scrollPhysics: BouncingScrollPhysics(),
          backgroundDecoration: BoxDecoration(color: Colors.black),
          loadingBuilder: null, // ...
          loadFailedChild: null, // ...
          onPageChanged: _onPageChanged,
          pageController: _controller,
          itemCount: widget.images.length,
          builder: (BuildContext context, int index) => PhotoViewGalleryPageOptions(
            initialScale: PhotoViewComputedScale.contained,
            minScale: PhotoViewComputedScale.contained / 2,
            maxScale: PhotoViewComputedScale.covered * 2,
            filterQuality: FilterQuality.high,
            onTapDown: (c, d, v) => _onPointerDown(d.globalPosition),
            onTapUp: (c, d, v) => _onPointerUp(d.globalPosition),
            imageProvider: LocalOrNetworkImageProvider(
              url: () async => widget.images[index],
              file: () async => null,
            ),
          ),
        ),
      ),
      Positioned(
        bottom: 0,
        child: xxx,
      ),
    ],
  ),
),
```

Actions such as:

```dart
if (xxx) {
  _show = !_show;
  if (mounted) setState(() {});
}
```

**Screenshots**

Before `setState` and after `setState`

<img height=500 src="https://user-images.githubusercontent.com/31433480/85531801-aa07f880-b641-11ea-9c68-80c014a97d36.png" /> <img height=500 src="https://user-images.githubusercontent.com/31433480/85531650-893fa300-b641-11ea-9901-48df7090907f.png" />

**Comment by IBM9100** [comment]
Any updates?

**Comment by Aoi-hosizora** [comment]
I saw this issue: https://github.com/flutter/flutter/issues/22514#issuecomment-451663033.

I think this black flash is invoked by the setState without `KeepAlives`. I wonder how can I set keepAlive for `PhotoViewGallery` just like `ListView`.

**Comment by Aoi-hosizora** [comment]
Oh, after reading the source code of https://github.com/Baseflow/flutter_cached_network_image/blob/develop/lib/src/image_provider/_image_provider_io.dart#L116-L126, I know how to solve my problem :)

If two `ImageProvider` are equals, the image data from the first provider will be loaded from network or other places (slow), and later it will be loaded from memory (or other ways, I have no idea, but very quickly) from the secold provider. So in this way (care for the `bool operator ==(dynamic other)` in `ImageProvide`), will the `PhotoViewGallery` not flash.

By the way, if I use `CachedNetworkImageProvider` directly, this problem will not be invoked. From the above code, you can see that the `LocalOrNetworkImageProvider` is wroten by me, so I update the `operator==` (see the following code) and finally solve my problem.

```dart
  @override
  bool operator ==(dynamic other) {
    if (other is LocalOrNetworkImageProvider) {
      return url == other.url && file == other.file && scale == other.scale;
    }
    return false;
  }

  @override
  int get hashCode => hashValues(url, file, scale);
```
