### ISSUE TITLE
[BUG] Null pointer Exception

### ISSUE THREAD

**Issue by wh1990xiao2005** [fireslime/photo_view#302]
Error Message:

The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()

Stack:
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      int./ (dart:core-patch/integers.dart:30:36)
#2      PhotoViewDefaultLoading.build (package:photo_view/src/photo_view_default_widgets.dart:25:39)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...

**Comment by renancaraujo** [comment]
Do you have more info or examples to reproduce it?

**Comment by yy3333333** [comment]
@wh1990xiao2005     同问，怎么办  Same problem ？how do?  @fireslime

**Comment by yiguozhen0510** [comment]
遇到同样的问题，请问问题解决了吗？没有解决的话，为什么这个issue被关闭了？

**Comment by renancaraujo** [comment]
Please, lets keep the discussion in english.
