### ISSUE TITLE
Is possible to disable the zoom and keep the scroll?

### ISSUE THREAD

**Issue by gbmiranda** [fireslime/photo_view#319]
Hello, I was wondering if it is possible to disable the zoom but keep the scroll.

I was also wondering if it is possible to disable the zoom out effect, as in the image below:

![IMG_9133](https://user-images.githubusercontent.com/8632216/90827981-957b7000-e313-11ea-90f9-13f74e53c0b3.PNG)

**Comment by Dohmanlechx** [comment]
@renancaraujo It would be really nice if you gave an example. I successfully created my own controller overriding those but no idea how I put it in actual use.

**Comment by mscherer82** [comment]
I did it like that:
```

class MyPC extends PhotoViewController {
  @override
  void set scale(double scale) {
    // TODO: implement scale
    super.scale = 1.0;
  }

  @override
  void updateMultiple({Offset position, double scale, double rotation, Offset rotationFocusPoint}) {
    // TODO: implement updateMultiple
    super.updateMultiple(position: position, scale: 1.0, rotation: rotation, rotationFocusPoint: rotationFocusPoint);
  }

  void forceUpdateMultiple({Offset position, double scale, double rotation, Offset rotationFocusPoint}) {
    // TODO: implement updateMultiple
    super.updateMultiple(position: position, scale: scale, rotation: rotation, rotationFocusPoint: rotationFocusPoint);
  }
}
```

```
PhotoViewGalleryPageOptions(
                  controller: pvc, // Instance of MyPC 
                  imageProvider: getImageProvider(p.regularURL),
                  minScale: PhotoViewComputedScale.contained * 1,
                  maxScale: PhotoViewComputedScale.covered * 3,
            )
```

Double tap still zooms.

**Comment by renancaraujo** [comment]
@mscherer82  
> You can extend it and override `updateMultiple` and `setScale` 

Have you tried overriding `setScale` ?

**Comment by renancaraujo** [comment]
Since we got no answer for a while, I am automatically closing this issue for organisation sake.
  If there is any news on that, fell free to retake the discussion.
