### ISSUE TITLE
on ios  flutter 1.20 Clicking on an image tries to go back, but sometimes it doesn't work

### ISSUE THREAD

**Issue by DNetORM** [fireslime/photo_view#324]
Today, when I upgraded flutter to 1.20, I found that sometimes clicking back doesn't work on IOS iphone7

 GestureDetector(
                onTap: () {
                  Navigator.of(context).pop();
                },
                child: PhotoViewGallery(
                  pageOptions: renderPhotos(),
                  loadingChild: widget.loadingChild,
                  backgroundDecoration: widget.backgroundDecoration,
                  pageController: widget.pageController,
                  onPageChanged: onPageChanged,
                ),
              ),

ontap sometimes can trigger  sometimes can not trigger，i dont know why,confusing,When I switch between pictures, there is an image that can be clicked. When there is only one image, it can't be clicked again，So I guess, is there any component that blocks the image and makes the click invalid?Originally, we wanted to go online in a few days, but we didn't expect that 1.20 encountered this problem,bad luck

**Comment by shaohui93** [comment]
me too

**Comment by renancaraujo** [comment]
That might have been fixed by #326

**Comment by shaohui93** [comment]
This solved my problem #326
