### ISSUE TITLE
[BUG] Inconsistent Image Size on Slide

### ISSUE THREAD

**Issue by ishandeveloper** [fireslime/photo_view#329]
**Describe the bug**
I am using PhotoViewGallery.builder to show a full-screen image gallery, but I'm running into this weird issue, where the size of the image just shrinks down [if it has a landscape orientation], or scales up [if portrait] whenever I'm sliding to a new image. It's just so inconsistent and not a smooth swipe experience.

**To Reproduce**
Steps to reproduce the behavior.

This is the basic code for how I'm using the builder widget. In my actual implementation, I'm using it inside a stack to overlay, an Image Index Indicator.

```dart
 PhotoViewGallery.builder(
                pageController:
                    PageController(initialPage: widget.currentImageIndex),
                onPageChanged: indexChangeHandler
                scrollPhysics: BouncingScrollPhysics(),
                builder: (BuildContext context, int index) {
                  return PhotoViewGalleryPageOptions(
                      imageProvider:
                          CachedNetworkImageProvider(widget.images[index]),
                      initialScale: PhotoViewComputedScale.contained,
                      minScale: PhotoViewComputedScale.contained,
                      maxScale: PhotoViewComputedScale.covered * 3,
                      controller: _photoViewController);
                },
                itemCount: widget.images.length,
                loadingBuilder: (context, event) => CustomProgressIndicator()
              ),
```

* Just make sure to have around 3 or more images in the gallery.
* Try swiping to next image items, slowly and you should be able to reproduce the issue.

**What is the current behavior?**
As I described above in the bug description, the size of the image is inconsistent while sliding.

**What is the expected behavior?**

Ideally, the size of the image, should not shrink down more than the minScale/initialScale size, in case of images with landscape orientation and should not exceed the initialScale in case of portrait orientation images during the swipe.

**Screenshots**

Attached Gif might take some time to load.

<img src="https://user-images.githubusercontent.com/54989142/91344247-53629a80-e7fb-11ea-8b9e-1e20e351566b.gif" height="450">

**Is this a *feature* or report a *bug*?**
It's a bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. The output of flutter doctor can help too. **

I can create a minimal demo of the issue, if you're not able to reproduce using the above code.

**flutter doctor -v**
```
[√] Flutter (Channel master, 1.22.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-1.0.pre at C:\src\flutter
    • Framework revision e3c7fb5bef (2 weeks ago), 2020-08-11 08:59:20 -0700
    • Engine revision 9b4ce4e3a0
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)
```

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**

I'm running on master channel of Flutter 1.22 and using the 0.10.2 version of photo_view package. I was able to produce this on my OnePlus 7 Pro, android device. Haven't tried yet on iOS, I can test it out later, to see if it's reproducible.

**Additional Context**

One weird thing I noticed, previously I was using **photo_view : 0.9.2** version and I didn't seem to notice this issue. But I had to upgrade to 0.10.2, because of #252 

Let me know, If this is an expected behaviour, and how I can overcome this.

**Comment by renancaraujo** [comment]
It is probably caused by the shared controller.

**Comment by ishandeveloper** [comment]
Yes @renancaraujo , that was the underlying issue. I removed the `PhotoViewController()` from my `PhotoViewGalleryOptions` and it seems to solve the issue. **Thanks for the quick response !** 👍 

For anyone else, facing a similar issue in the future, can just remove `controller` parameter the above code like this

```dart

 PhotoViewGallery.builder(
        pageController:
            PageController(initialPage: widget.currentImageIndex),
        onPageChanged: indexChangeHandler
          scrollPhysics: BouncingScrollPhysics(),
        builder: (BuildContext context, int index) {
          return PhotoViewGalleryPageOptions(
              imageProvider:
                  CachedNetworkImageProvider(widget.images[index]),
              initialScale: PhotoViewComputedScale.contained,
              minScale: PhotoViewComputedScale.contained,
              maxScale: PhotoViewComputedScale.covered * 3,
              );
             },
             itemCount: widget.images.length,
             loadingBuilder: (context, event) => CustomProgressIndicator()
           ),
```

**Comment by Devbymitch** [comment]
I ran into this and solved it with this solution, however I wanted the images to revert back to their original scale when swiping to a new image. I solved this by adding the controller back in like: `controller: new PhotoViewController()`

**Comment by SilkeNL** [comment]
I have this issue as well but no controller on the PageOptions. My code:

`PhotoViewGallery.builder(
            pageController: pageController,
            backgroundDecoration: BoxDecoration(
              color: Colors.white,
            ),
            itemCount: imageUrls.length,
            builder: (BuildContext context, int index) {
              return PhotoViewGalleryPageOptions(
                imageProvider:
                    CachedNetworkImageProvider(imageUrls[currentIndex]),  //imageUrls is a List<String> of length 3
                initialScale: PhotoViewComputedScale.contained * 1,
                maxScale: PhotoViewComputedScale.contained * 2,
                minScale: PhotoViewComputedScale.contained * 0.8,
              );
            },
            loadingBuilder: (context, event) {
              return Center(
                child: Container(
                  width: 48,
                  height: 48,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              );
            },
            onPageChanged: (int index) {
    setState(() {
      currentIndex = index;
    });

    pageController.jumpToPage(index);
  },
          )`

**Comment by renancaraujo** [comment]
@SilkeNL Why are you getting `CachedNetworkImageProvider(imageUrls[currentIndex])` instead of `CachedNetworkImageProvider(imageUrls[index])` with `idnex` given by the builder?

**Comment by SilkeNL** [comment]
Because I use the index more ways, not all in that builder

**Comment by renancaraujo** [comment]
PhotoViewGalleryPageOptions should eceive the image of each page, not just the current one.

**Comment by SilkeNL** [comment]
I am not sure I understand. Form https://github.com/fireslime/photo_view/blob/master/example/lib/screens/examples/gallery/gallery_example.dart :

      `PhotoViewGalleryPageOptions _buildItem(BuildContext context, int index) {
          final GalleryExampleItem item = widget.galleryItems[index];          //They also set only one image?
          return item.isSvg
              ? PhotoViewGalleryPageOptions.customChild(
                  child: Container(
                    width: 300,
                    height: 300,
                    child: SvgPicture.asset(
                      item.resource,
                      height: 200.0,
                    ),
                  ),
                  childSize: const Size(300, 300),
                  initialScale: PhotoViewComputedScale.contained,
                  minScale: PhotoViewComputedScale.contained * (0.5 + index / 10),
                  maxScale: PhotoViewComputedScale.covered * 4.1,
                  heroAttributes: PhotoViewHeroAttributes(tag: item.id),
                )
              : PhotoViewGalleryPageOptions(
                  imageProvider: AssetImage(item.resource),
                  initialScale: PhotoViewComputedScale.contained,
                  minScale: PhotoViewComputedScale.contained * (0.5 + index / 10),
                  maxScale: PhotoViewComputedScale.covered * 4.1,
                  heroAttributes: PhotoViewHeroAttributes(tag: item.id),
                );
        }`
        
How can I give multiple urls to `PhotoViewGalleryPageOptions` ?

**Comment by renancaraujo** [comment]
See this line?
`final GalleryExampleItem item = widget.galleryItems[index];  `

We are fetchong the subject from the index that the builder provided, not one that you are storing in a state. 

In your previous example you should not do this:
`imageProvider: CachedNetworkImageProvider(imageUrls[currentIndex]),`

But this:
`imageProvider: CachedNetworkImageProvider(imageUrls[index]),`

**Comment by SilkeNL** [comment]
You're right, that fixed it. Thank you! @renancaraujo
