### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by Renatinaveen** [fireslime/photo_view#330]
I could able to add the paginated data, but the controller position shifts to the starting index. Is there any walkaround to achieve this?

Take example of Pinterest swiping right they perform the pagination but when the new data has loaded the controller doesn't shift to the starting index.

**Comment by renancaraujo** [comment]
Is this about the gallery?

**Comment by Renatinaveen** [comment]
Yes, @renancaraujo I have solved the issue for now. what I have done is the package code was mentioning the initial child as final i have removed it and when the data is loaded I'm setting the initial value to the previous index.

**Comment by renancaraujo** [comment]
Where do we mention that? If so, we need to remove it.

**Comment by Renatinaveen** [comment]
@renancaraujo Sorry, it's from the flutter package page_view file. I have changed it there.
