### ISSUE TITLE
[BUG] Double Tap on Different Android Devices

### ISSUE THREAD

**Issue by ishandeveloper** [fireslime/photo_view#331]
**Describe the bug**
I am using PhotoViewGallery.builder to show a full-screen image gallery. But, I ran into this issue, where the double-tap gesture recognition is just not consistent among different android devices, i.e. on some devices it works as expected, but on others it just shows some unexpected behaviours.

**To Reproduce**
Steps to reproduce the behavior.

```dart
 PhotoViewGallery.builder(
        pageController:
            PageController(initialPage: widget.currentImageIndex),
        onPageChanged: indexChangeHandler
          scrollPhysics: BouncingScrollPhysics(),
        builder: (BuildContext context, int index) {
          return PhotoViewGalleryPageOptions(
              imageProvider:
                  CachedNetworkImageProvider(widget.images[index]),
              initialScale: PhotoViewComputedScale.contained,
              minScale: PhotoViewComputedScale.contained,
              maxScale: PhotoViewComputedScale.covered * 3,
              );
             },
             itemCount: widget.images.length,
             loadingBuilder: (context, event) => CustomProgressIndicator()
           ),
```

**What is the current behavior?**
I tested on two of my android devices **OnePlus 7 Pro** and **Samsung Galaxy Note 9** and noticed that the double tap to zoom/zoom out interaction was not consistent among both of them.

While it worked as expected on OnePlus device, on the Samsung device, it just does not zoom out. You can get a more clear idea from the GIFs attached below, to better understand what I'm trying to describe.

**Expected behavior**
The gesture detector interaction should be consistent across all devices, at least running on the same OS (Android).

**Screenshots**
P.S. The GIFs might take some time to load.

**OnePlus 7 Pro** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Samsung Galaxy Note 9**  
  
<img src="https://user-images.githubusercontent.com/54989142/91644484-fc0e3580-ea59-11ea-99c6-dfe119dfbe68.gif" alt="OnePlus 7 Pro" height="500em"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="https://user-images.githubusercontent.com/54989142/91644486-fe708f80-ea59-11ea-9be0-91b8dfb32176.gif" alt="Galaxy Note 9" height="500em">

**Is this a *feature* or report a *bug*?**
Bug Report

**`flutter doctor -v`**
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**

I'm using the `photo_view : 0.10.2` package version. This does work fine on iOS, but results were different while testing on different android devices.

I tried using a bunch of different images with different resolutions, but the issue was still reproducible.

Let me know if there's anything we can do to fix this in the package itself, or maybe if this is an issue with the gestureRecognizier in Flutter framework itself.

**Comment by renancaraujo** [comment]
Check #293
