### ISSUE TITLE
[BUG] White Screen

### ISSUE THREAD

**Issue by muhammadsaddamnur** [fireslime/photo_view#338]
**Describe the bug**
E/Adreno-GSL( 5962): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL( 5962): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory

**What is the current behavior?**
white screen, if fast swipe image on photoview

**Is this a *feature* or report a *bug*?**
bug

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1082], locale
    en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.48.2)
[√] Connected device (1 available)

**Comment by renancaraujo** [comment]
Looks like a platform issue, is this a temporary white screen? Maybe the fetch of the images, you can try to [cache your images](https://flutter.dev/docs/cookbook/images/cached-images).

**Comment by BernardinD** [comment]
Was there ever a solution for this? I believe I have the same issue when I put a ScrollBar on the Gallery
