### ISSUE TITLE
zoomable loadingbuilder

### ISSUE THREAD

**Issue by clragon** [fireslime/photo_view#339]
**Is your feature request related to a problem? Please describe.**
I use a lower res version of the picture I want to show the user when loading.
The loading builder cannot be zoomed or otherwise interacted with,
however I would like to be able to use the loadingbuilder like the actual picture,
with zoom interactions, drag etc. The actual picture could then replace the loadingbuilder without
changing the zoom or position of the loadingbuilder, basically just silently upgrading the quality.

**Describe the solution you'd like**
There are probably several solutions for this.
The ones I can think of is allowing to zoom the loading builder, 
or allowing to provide another picture provider as the loading builder.
it would also be great if the loadingbuilder was just replaced by the fully loaded picture in the same zoom position the user is in, so the loading of the full picture isnt an interruption.

**Describe alternatives you've considered**
Currently I just show the low res picture with a loading indicator. 
But since it cannot be interacted with, this is confusing users.

**Comment by rivalinz** [comment]
loadingBuilder: (context, url_img) => LoadingImg(context),

this work for me.

**Comment by clragon** [comment]
I probably wasnt clear enough on what I want, my bad.
I am pretty sure providing a widget to the loadingBuilder right now _will_ display the picture,
but you still cannot interact with it like with the fully loaded picture from the builder,
which is the behaviour I would like to see.

**Comment by clragon** [comment]
I think I have solved this.
In a werid way, but I think I got it.

Basically, if you want to load in a lower res version while the high res version is loading, do the following:


```dart
return PhotoViewGallery.builder(
  builder: (context, index) {
      return PhotoViewGalleryPageOptions.customChild(
      child: CachedNetworkImage(
          imageUrl: posts[index].highres,
          placeholder: (context, url) => CachedNetworkImage(
              imageUrl: posts[index].lowres,
              placeholder: (context, url) => Center(
                  child: Container(
                  height: 20,
                  width: 20,
                  child: CircularProgressIndicator(),
                  ),
              ),
          ),
      ),
      )
  },
)
```

you use a custom child page, and then nest 2 image widgets into each other, where as the lower resolution one is the placeholder or loading builder for the higher resolution one.

**Comment by cherrybiu** [comment]
There is an another question. If I used `PhotoViewGalleryPageOptions`, not `customChild`, how can I show the lower res version of the picture

**Comment by clragon** [comment]
You can use `loadingBuilder` but it will not be zoomable.
If you want to replace he low res picture with high res
while the user can zoom, you have to use custom child.

**Comment by cherrybiu** [comment]
Sorry , I wanted to comment the #312 .  `loadingBuilder` can' t satisfy my need. I need to see the pic once I tap it . I have same problem with you mentioned above. In my opinion, it seems moving ` loadingBuilder ` to PhotoViewGalleryPageOptions can solve all the situation.

**Comment by clragon** [comment]
Yes, that makes perfect sense, I agree.
Should I reopen #312?
