### ISSUE TITLE
Please, support custom PageView!

### ISSUE THREAD

**Issue by violet-dev** [fireslime/photo_view#343]
There was a bug where images flickered and images were not cached even with `precacheImage`.
So I changed the `PageView` to `PreloadPageView`(https://pub.dev/packages/preload_page_view) and adjusted the `preloadPagesCount` and the problem was completely resolved.

Here is my custom `PhotoViewGallery` class using `PreloadPageView`.
https://github.com/project-violet/violet/commit/af6122504ef5eb4c82c17ee5db1f55316c4e9b07#diff-142e88c7031ebc8424a95c578cdbe270R240

Or please, provide the option like `cacheExtent` to allow the page to be preloaded.

Thanks for making a nice library!

**Comment by clragon** [comment]
And this isnt resolved by using precache?
```dart
precacheImage(
  OptimizedCacheImageProvider(
    _urlCache[index],
    headers: _headerCache[index],
  ),
  context,
);
```
interesting because this seems to work perfectly fine for me, 
using `precacheImage` and `cached_network_image`.

**Comment by renancaraujo** [comment]
You always can create your own gallery using any pageview you want, that why PhotoView exists. 

Just be careful to wrap your PageView with `PhotoViewGestureDetectorScope` as the built-in gallery does.
