### ISSUE TITLE
Darken image option for PhotoView

### ISSUE THREAD

**Issue by hamberluo** [fireslime/photo_view#344]

**Comment by clragon** [comment]
Could you describe what exactly you want here? 
The title doesnt really make it clear imo.
If you just want a dark overlay, does something like
```dart
Container(
  color: Colors.black38,
  child: PhotoView(...),
),
```
not work for you?

**Comment by hamberluo** [comment]
hi @clragon, can this affect the hero animation?

**Comment by clragon** [comment]
Yes it can, but it will be annoying to produce.

You can either;

1. Not set the hero attributes, wrap the PhotoView in a custom hero and container
```dart
Hero(
  tag: 'my_image',
  child: Container(
    color: Colors.black38,
    child: PhotoView(...),
  ).
).
```

2. or use the custom child option
```dart
PhotoView.customChild(
  heroAttributes: PhotoViewHeroAttributes(
    tag: 'my_image',
  ),
  child: Container(
    color: Colors.black38,
    child: Image(...).
  ),
),
```

In case you are using a gallery, you can use `PhotoViewGalleryPageOptions.customChild`.

Both of these options will probably have their own downsides,
so you will have to try out what works better for you.

**Comment by hamberluo** [comment]
hi @clragon, 
in my scene, I need a build callback before Hero in `PhotoViewCore`.
For an example,
```
  Widget _buildHero() {
    return heroAttributes != null
        ? Hero(
            tag: heroAttributes.tag,
            createRectTween: heroAttributes.createRectTween,
            flightShuttleBuilder: heroAttributes.flightShuttleBuilder,
            placeholderBuilder: heroAttributes.placeholderBuilder,
            transitionOnUserGestures: heroAttributes.transitionOnUserGestures,
            child: _buildChild(),
          )
        : _buildChild();
  }
```
using a widget builder to wrapper `_buildChild()` as a parameter and return a `Widget`.

**Comment by clragon** [comment]
hi @hamberluo,
I'm not sure what youre trying to achieve.

Would this not work?

```dart
PhotoView.customChild(
  heroAttributes: heroAttributes,
  child: (){
     return heroAttributes != null
       ? Hero(
         tag: heroAttributes.tag,
         // ....
         child: _buildChild(),
        )
        : _buildChild();
  }(),
),
```

**Comment by renancaraujo** [comment]
Hey, @hamberluo heave you figured this out? Couldn't quite understand what is being discussed here.
