### ISSUE TITLE
the GestureDetector in some iOS can't response

### ISSUE THREAD

**Issue by EchoPuda** [fireslime/photo_view#348]
**Describe the bug**
I add a GestureDetector to contains the PhotoViewGallery.builder, and It can't response in some iOS device.
when it happened, I change to other page, then it response the tap.

**Comment by EchoPuda** [comment]
use disableGestures: true and it work

**Comment by githublsy** [comment]
> use disableGestures: true and it work

use disableGestures will lose doubleTapGesture

**Comment by EchoPuda** [comment]
@githublsy Now I change the GestureDetector in local, Its gesture event conflict.

**Comment by githublsy** [comment]
> Now I change the GestureDetector in local, Its gesture event conflict

how u fix this problem? could u show me some code

**Comment by EchoPuda** [comment]
Hi @githublsy 
Like this:
In photo_view_gesture_detector.dart
![image](https://user-images.githubusercontent.com/48596516/97277816-ebb8e200-1873-11eb-9b97-33c0f7b2bb61.png)
![image](https://user-images.githubusercontent.com/48596516/97277961-17d46300-1874-11eb-8337-4a3c3b6bd8b4.png)

you can remove the onTapUp and onTapDown or not.
And then add all the relevant "onTap" in photo_view_gallery, photo_view_core, photo_view_wrappers, photo_view ...
(You can find them by “onTapUp”)

Finally:
![image](https://user-images.githubusercontent.com/48596516/97278404-b791f100-1874-11eb-8a6e-51cb6700b6da.png)

**Comment by githublsy** [comment]
i will try it later ,thanks a lot!

**Comment by githublsy** [comment]
@EchoPuda i will try it later, thanks a lot!
