### ISSUE TITLE
Question: Keep zoomed image visible part within container (same as PhotoViewGallery default behaviour)

### ISSUE THREAD

**Issue by CarlosCabarcos** [fireslime/photo_view#352]
Hi everyone. I'm pretty new to flutter and app programming in general, so apologies in advance in case I'm asking something obvious. I used this plugin in a project but there's something I can't seem to get to work.

I used a PhotoViewGallery and just out of the box, if I zoom any of the gallery elements, the visible part of the zoomed image stays withing the gallery's container, it's like "looking at the zoomed image through a window".

However, I tried using a simple PhotoView for another purpose and I can't get it to work in the same way. When I zoom into the image, I see the full image, exceeding the size of its container, overlapping on some elements of the screen and going under others (depending on build order within the widget tree of the screen).

I was wondering how I could manage to keep the visible part of the zoom image within the confines of its container (same as the gallery).

Thank you very much.

**Comment by CarlosCabarcos** [comment]
I ended up using a PhotoViewGallery with a single photo instead of a PhotoView, but I'm sure there must be a way to achieve what I was trying to do using a PhotoView. If anyone knows how to, I would still be very happy to hear it...

**Comment by renancaraujo** [comment]
That is a very good question and there is nothing wrong with it. Sorry for the delay, but you can use [ClipReact](https://api.flutter.dev/flutter/widgets/ClipRect-class.html) around PhotoView to achieve that.

```dart
ClipRect(
  child: PhotoView(
   ...
  ),
)
```
