### ISSUE TITLE
[BUG] Not able to compile photo_view project cloned from github

### ISSUE THREAD

**Issue by kamleshwebtech** [fireslime/photo_view#353]
Cloned project from github is not working, getting an error message in console:

AndroidManifest.xml could not be found.
Please check D:\kamlesh\development\test\photo_view\example\android\AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android\AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by kamleshwebtech** [comment]
I have one more request. Kindly post a simple and proper example to make more popular this package at 

https://pub.dev/packages/photo_view/example

Thanks a lot!

**Comment by renancaraujo** [comment]
Yeah, we have to run `flutter create .` on the `example` directory after clonning. This will solve your problem.

**Comment by renancaraujo** [comment]
> Kindly post a simple and proper example at...

Well, that is automatically generated from the main file of the example app, do it is pretty much the same thing.
Do you have an idea to tackle that?
