### ISSUE TITLE
[BUG] Type 'ImageErrorWidgetBuilder' not found

### ISSUE THREAD

**Issue by RicardoJFerreira** [fireslime/photo_view#356]
Just by including this packaging in my project and importing it to some screen, I get these errors:

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.10.2/lib/photo_view.dart:308:9: Error: Type 'ImageErrorWidgetBuilder' not found.
  final ImageErrorWidgetBuilder errorBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.10.2/lib/photo_view.dart:308:9: Error: 'ImageErrorWidgetBuilder' isn't a type.
  final ImageErrorWidgetBuilder errorBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.10.2/lib/src/photo_view_wrappers.dart:38:9: Error: Type 'ImageErrorWidgetBuilder' not found.
  final ImageErrorWidgetBuilder errorBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.10.2/lib/src/photo_view_wrappers.dart:38:9: Error: 'ImageErrorWidgetBuilder' isn't a type.
  final ImageErrorWidgetBuilder errorBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.10.2/lib/src/photo_view_wrappers.dart:192:21: Error: 'errorBuilder' isn't a function or method and can't be invoked.
      return widget.errorBuilder(context, _lastException, _stackTrace);

Can someone help me figuring this out?

**Comment by jpieres** [comment]
Same as reported by @RicardoJFerreira

**Comment by renancaraujo** [comment]
Which version of flutter are you using? Which version of photo_view?

**Comment by gilnuy** [comment]
flutter : v1.12.13+hotfix.9
photo_view : 0.10.3

**Comment by renancaraujo** [comment]
Hey, just gave a look into it and it looks like your flutter version is quite outdated. 
This happens because photo_view uses things that were added flutter around flutter 1.17.
You can either update your flutter version or use an older version of photo_view.
