### ISSUE TITLE
[BUG]Multi-image sliding is normal on the iOS emulator, But the Iphone occasionally slides out of order

### ISSUE THREAD

**Issue by Hynsen** [fireslime/photo_view#357]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**What is the current behavior?**

**Expected behavior**

**Screenshots**

**Is this a *feature* or report a *bug*?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. The output of flutter doctor can help too. **

**What is the expected behavior?**

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**

**Additional context**

**Comment by renancaraujo** [comment]
Do you bother to at least fill the questions in the issue body?
