### ISSUE TITLE
[BUG] imageprovider not working with image.file widget

### ISSUE THREAD

**Issue by kamleshwebtech** [fireslime/photo_view#360]
This plug-in's imageprovider attribute does not work with Image.file widget. Please see my below code:

PhotoView(
  imageProvider: Image.file(File(photoFilePath), ),
)

and suggest me how can i use image.file with photo_view widget. Thanks a lot.

**Comment by renancaraujo** [comment]
Because `Image.file` is not an image provider. For that, you need to use [`FileImage`](https://api.flutter.dev/flutter/painting/FileImage-class.html).
