### ISSUE TITLE
Double Tap Zoom #HelpWanted

### ISSUE THREAD

**Issue by GGLabCenter** [fireslime/photo_view#373]
Hi,

thanks for the beautiful plugin. By default - with a double-tap I get a soft-zoom, and with another one I get a deeper-zoom. An extra double-tap will reset the zoom to 0. I would like to have directly the deeper-zoom with a single double-tap, and a reset if I repeat the action.

How I can achieve that? Thanks in advance!

**Comment by renancaraujo** [comment]
You want to customize the scale state cycle. 

The default one is:
```dart
PhotoViewScaleState defaultScaleStateCycle(PhotoViewScaleState actual) {
  switch (actual) {
    case PhotoViewScaleState.initial:
      return PhotoViewScaleState.covering;
    case PhotoViewScaleState.covering:
      return PhotoViewScaleState.originalSize;
    case PhotoViewScaleState.originalSize:
      return PhotoViewScaleState.initial;
    case PhotoViewScaleState.zoomedIn:
    case PhotoViewScaleState.zoomedOut:
      return PhotoViewScaleState.initial;
    default:
      return PhotoViewScaleState.initial;
  }
}
```

To achieve what you want, you need to create you own cycle. I guess this works for you:

```dart
PhotoViewScaleState myScaleStateCycle(PhotoViewScaleState actual) {
  switch (actual) {
    case PhotoViewScaleState.initial:
      return PhotoViewScaleState.originalSize;
    default:
      return PhotoViewScaleState.initial;
  }
}
```

and then pass your cycle function to PhotoView as the `scaleStateCycle` option.

**Comment by GGLabCenter** [comment]
Works perfectly as expected, thanks!
