### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by DevNico** [fireslime/photo_view#374]
Null safety is in the second technical preview stage with flutter core support it's therefore time to start migrating packages. I'd be happy to open a PR for Null Safety if it isn't already in the works.

**Comment by renancaraujo** [comment]
I was about to open this issue. Thanks!
Go ahead as I work on some bugs.

**Comment by aliyazdi75** [comment]
Hi, any updates? All of my dependencies have been migrated except this.

**Comment by DevNico** [comment]
The PR is open just waiting for someone to review and or merge it.

**Comment by fzyzcjy** [comment]
Hi looking forward to this update! Since flutter has make null safety **stable** today!
