### ISSUE TITLE
Back screen by swipe down

### ISSUE THREAD

**Issue by webaddicted** [fireslime/photo_view#377]
Hi

Please add video feature in which when swipe down then back to previous screen.
Check attach video.

Thank you ❤
[back handle.zip](https://github.com/fireslime/photo_view/files/5611733/back.handle.zip)

**Comment by renancaraujo** [comment]
Im not downloading this. If you are requesting a feature, please decribe it as the issues templates says or contact us via discord.

**Comment by webaddicted** [comment]
Hi,
I want feature like every app provide when image open in full screen then when i swipe down on image then it call back. 

You can check on whatsapp, open any person dp in full image then swipe down, after swipe down it back from image it give amazing experience.

You can provide swipe down event in your package. User can handle back by it's own way. 

Thanks in advance.

**Comment by clragon** [comment]
I think you are looking for a feature like the pull request #273 introduces.
