### ISSUE TITLE
Keeping the scale and rotate state after rebuild

### ISSUE THREAD

**Issue by mehmetyilmaz001** [fireslime/photo_view#380]
Hi,

I am using the PhotoView widget inside a container and drawing some line in my case and this change cause rebuilds.

Is there any way the keep the scale and rotate state after rebuilds?

**Comment by renancaraujo** [comment]
Yah, use [controllers](https://pub.dev/documentation/photo_view/latest/photo_view/PhotoView-class.html#controllers).
