### ISSUE TITLE
[BUG] wont come down in pub get properly.

### ISSUE THREAD

**Issue by amigax** [fireslime/photo_view#382]
Running "flutter pub get" in salto-flutter...                   
Error on line 1, column 1 of https://pub.dartlang.org/api/packages/%2F%2Fphoto_view: "name" field doesn't match expected name "//photo_view".
pub get failed (65; Error on line 1, column 1 of https://pub.dartlang.org/api/packages/%2F%2Fphoto_view: "name" field doesn't match expected name "//photo_view".)

**Comment by renancaraujo** [comment]
I am not sure what this means but looks like you got some extra slashed there. 
Use `https://pub.dartlang.org/api/packages/photo_view` not `https://pub.dartlang.org/api/packages/%2F%2Fphoto_view`
