### ISSUE TITLE
Implementing with cached image

### ISSUE THREAD

**Issue by Princewil** [fireslime/photo_view#390]
Equipping this package with #cached_network_image package or a custom cache will go along way, for obvious reasons. 
since with can't use the  widget provided by #cached_network_image package with our #photoView widget, caching under the hood should be the only option.

**Comment by clragon** [comment]
There is no need for that, you can use `cached_network_image` with this package just fine.
Either by using a `CachedNetworkImageProvider` or by using a `PhotoView.customChild` and the `CachedNetworkImage` widget.

**Comment by Princewil** [comment]
Oh!
Alright. I will play around with it.
Thanks alot

**Comment by renancaraujo** [comment]
It seems this question was answered
