### ISSUE TITLE
[BUG] Listview in a PhotoViewGallery is blocked/lagged when scroll down

### ISSUE THREAD

**Issue by AverageChau** [fireslime/photo_view#392]
When I put ListView of image in a PhotoViewGalleryPageOptions.customChild in a PhotoViewGallery like this 
```
   PhotoViewGallery(
        pageOptions: [
          PhotoViewGalleryPageOptions.customChild(
            minScale: 1.0,
            child: Container(
              color: Colors.grey,
              child: ListView(
                children: [
                  Image.asset(
                    'assets/image_sample.jpg',
                    fit: BoxFit.fitWidth,
                  ),
                  SizedBox(
                    height: 30,
                  ),
                  Image.asset(
                    'assets/image_sample.jpg',
                    fit: BoxFit.fitWidth,
                  ),
                  SizedBox(
                    height: 30,
                  ),
                  Image.asset(
                    'assets/image_sample.jpg',
                    fit: BoxFit.fitWidth,
                  ),
                  SizedBox(
                    height: 30,
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
```
If I zoomed-in a little bit and try to scroll from page 1 to the last page, it got block (drag down but the view is not down) or stuck multiple time on the way down. Full code here, [github](https://github.com/AverageChau/PhotoViewListViewBug)

![bug](https://user-images.githubusercontent.com/25887242/107866431-68afac00-6ea3-11eb-99f5-0407e97afd47.gif)

**To Reproduce**
1. Zoomed in (must do) 
2. Try drag up and down

**Expected behavior**
- Smooth up and down.

**Comment by renancaraujo** [comment]
Are you zooming in an entire list? This use case seems to be more appropriate to use [InteractiveViewer](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html)
