### ISSUE TITLE
[BUG]photoViewController.position's given coordinate is not center of screen

### ISSUE THREAD

**Issue by choi-seung-min** [fireslime/photo_view#393]
**Describe the bug**
I got image's coordinate which have to be positioned to center of screen. I set offset(x, y) to photoViewController.position and it's not center.

![image](https://user-images.githubusercontent.com/39794966/108033635-a5340100-7077-11eb-9b9b-15c5a3c617d8.png)
The orange area's top-left edge is given to photoViewController.position.

after
![image](https://user-images.githubusercontent.com/39794966/108033672-b4b34a00-7077-11eb-9495-32dc4f1d1891.png)

**Expected behavior**
I expected the top-left position is centered to screen.

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
0.10.3

**Comment by poojabokdia** [comment]
@choi-seung-min  can you please explain how you fixed it ?

**Comment by poojabokdia** [comment]
@choi-seung-min  also if the coordinates are top left ? or centered? or bottomleft?
