### ISSUE TITLE
Can we display indicators (small dots at the bottom) in the gallery mode?

### ISSUE THREAD

**Issue by alvinkonda** [fireslime/photo_view#396]
It seems this feature is not available on the `PhotoViewGallery.builder` method. I think indicators are a must-have feature for any photo gallery plugin. If not possible, is it any other recommend method to work with them?

Thanks,
Alvin

**Comment by renancaraujo** [comment]
PhotoView aims to be flexible and provide a minimal API without redoing what is possible with the framework. 

PhotoViewGallery is a pageview, and thus you can implement your indicators with the same flexibility as the framework provides. Fort example you can use [Indicators](https://pub.dev/packages/page_view_indicators) to achieve that.
