### ISSUE TITLE
[BUG]How to handle error when url not exist, errorBuilder not working properly it throws the error 

### ISSUE THREAD

**Issue by manishrelani** [fireslime/photo_view#398]
PhotoViewGallery.builder(
      scrollPhysics: const BouncingScrollPhysics(),
      builder: (BuildContext context, int index) {
        return PhotoViewGalleryPageOptions(
          errorBuilder:
              (BuildContext context, Object exception, StackTrace stackTrace) {
            return Scaffold(
              backgroundColor: backgroundColor,
              body: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.error,
                      color: Colors.white,
                    ),
                    SizedBox(
                      height: 5,
                    ),
                    Text("No Image Found",
                        style: TextStyle(color: Colors.white))
                  ],
                ),
              ),
            );
          },
          imageProvider: NetworkImage(Complain_Image_Url + imageList[index]),
          initialScale: PhotoViewComputedScale.contained * 0.8,
          heroAttributes: PhotoViewHeroAttributes(tag: index),
        );
      },
      itemCount: imageList.length,
       loadingBuilder: (context, event) => Center(
        child: Container(
          width: 20.0,
          height: 20.0,
          child: CircularProgressIndicator(
            value: event == null
                ? 0
                : event.cumulativeBytesLoaded / event.expectedTotalBytes,
          ),
        ),
      ), 
      backgroundDecoration: BoxDecoration(color: backgroundColor),
      //  pageController: widget.pageController,
      //  onPageChanged: onPageChanged,
    );

**Comment by renancaraujo** [comment]
Please follow the template.

**Comment by manishrelani** [comment]
> Please follow the issue template.

can you send me the link. where I can find this issue.

**Comment by renancaraujo** [comment]
https://github.com/fireslime/photo_view/issues/new/choose

**Comment by kamleshwebtech** [comment]
IS THERE ANY SOLUTION OF THIS ISSUE? HOW CAN YOU CLOSE ANY RAISED ISSUE WITHOUT GIVING PROPER SOLUTION? THANKS.

**Comment by kamleshwebtech** [comment]
I have used errorBuilder attribute of PhotoView. Kindly tell me what is wrong with it and how can we solve it:

```
PhotoView(
  imageProvider: NetworkImage(
    widget.photoPath.toString(),
  ),
  errorBuilder: (BuildContext context, Object exception, StackTrace stackTrace) { 
    return Scaffold(
      body: Center(
        child: Text('Photo is not available, please try later.'),
      ),
    );
  },
)
```
