### ISSUE TITLE
[BUG] Stopped at error_patch.dart line 46 native "AssertionError_throwNew"; when first execute the photo_view plugin

### ISSUE THREAD

**Issue by inloop-tech** [fireslime/photo_view#412]
Describe the bug
I have created a screen with only photo_view widget. When first open that screen, my visual studio code will stop and pointed the error_patch.dart line 46 native "AssertionError_throwNew";
When I click the button to continue to execute the code. The next times open the screen seems it can normally display. However, open and close the same screen serval time, it shows a memory leak in my vs code debug code.

To Reproduce

    Create a screen with CarouselSlider.
    Click the CarouselSlider to open a screen to display photo using photo_view widget
    Start debug to execute the code
    Click on the CarouselSlider
    Stop and and pointed the error_patch.dart line 46 native "AssertionError_throwNew";
    Continue execute the code
    Open and close the screen with photo_view widget
    Sometime throw a memory leak error

What is the current behavior?
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.0.1 20B50 darwin-x64, locale en-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

Expected behavior
Open the screen photo_view widget without error

My Code:
class ProductImgViewer extends StatefulWidget {
final List imgList;

@override
ProductImgViewer(this.imgList, {Key key}) : super(key: key);

@override
_ProductImgViewerState createState() => _ProductImgViewerState();
}

class _ProductImgViewerState extends State {
int _current = 0;
List imageSliders;

Widget build(BuildContext context) {
return Scaffold(
appBar: T2AppbarBack("Index"),
body: Container(
constraints: BoxConstraints.expand(
height: MediaQuery.of(context).size.height,
),
child: PhotoView(
imageProvider: NetworkImage('https://picsum.photos/250?image=9'),
)),
);
}
}

Version:
Flutter: 2.0.3
photo_view: ^0.11.1
Android Version: 10

Thanks!!

**Comment by renancaraujo** [comment]
Thank you for the trace. Related to #406. Follow it there.

**Comment by inloop-tech** [comment]
Thanks for reopen the case. Please let me know if any additional information need for this issue.
