### ISSUE TITLE
[BUG] Long press gesture callback?

### ISSUE THREAD

**Issue by jinfagang** [fireslime/photo_view#414]
How to set a long press callback so that I can popup a bottom sheet indicate users to save that image?

**Comment by renancaraujo** [comment]
Check the open issues first. Feature request and questions are not bug.

**Comment by luohao123** [comment]
@renancaraujo Can u kindly reference a link of how to do it? I am facing same issue. Thanks in advance.

**Comment by renancaraujo** [comment]
Just click the "New issue" button. You will see the options.

**Comment by OpenJarvisAI** [comment]
@renancaraujo  Oh, dude, you just ignore the fearure request just cause op tagged bug, I think this is needed.
