### ISSUE TITLE
[BUG] Flutter SDK:2.3.0-24.0.pre. addAllowedPointer Method error

### ISSUE THREAD

**Issue by DizzyYang** [fireslime/photo_view#435]
Flutter SDK:2.3.0-24.0.pre

  @override
  void addAllowedPointer(PointerEvent event) {
    if (ready) {
      ready = false;
      _pointerLocations = <int, Offset>{};
    }
    super.addAllowedPointer(event);
  }

addAllowedPointer Method error

PointerEvent no longer exists

**Comment by EricPHassey** [comment]
Having the same issue here. Any work-arounds?

**Comment by DizzyYang** [comment]
@luanpotter @renancaraujo

Please give priority to the latest SDK changes

**Comment by DizzyYang** [comment]
@EricPHassey My solution is to correct the wrong way.

**Comment by EricPHassey** [comment]
> @EricPHassey My solution is to correct the wrong way.
> 
> ```
>  @override
>  void addAllowedPointer(PointerDownEvent event) {
>    if (ready) {
>      ready = false;
>      _pointerLocations = <int, Offset>{};
>    }
>    super.addAllowedPointer(event);
>  }
> ```

May I ask where this needs to be fixed? Is this an issue with this package? How or where do I need to apply this fix?

**Comment by DizzyYang** [comment]
photo_view/lib/src/core/photo_view_gesture_detector.dart

[https://github.com/fireslime/photo_view/blob/master/lib/src/core/photo_view_gesture_detector.dart#L101](url)

**Comment by Oumaima-abm** [comment]
> photo_view/lib/src/core/photo_view_gesture_detector.dart
> 
> [https://github.com/fireslime/photo_view/blob/master/lib/src/core/photo_view_gesture_detector.dart#L101](url)

When I did this, i face now a new error
" Error: 'PointerEventDown' isn't a type.
  void addAllowedPointer(PointerEventDown event) {
                         ^^^^^^^^^^^^^^^^
"

**Comment by Dekhnar** [comment]
any news ?

**Comment by Oumaima-abm** [comment]
> @EricPHassey My solution is to correct the wrong way.
> 
> ```
>  @override
>  void addAllowedPointer(PointerDownEvent event) {
>    if (ready) {
>      ready = false;
>      _pointerLocations = <int, Offset>{};
>    }
>    super.addAllowedPointer(event);
>  }
> ```

this solution worked for me
thanks

**Comment by inpactnosakae** [comment]
This sol

> 
> 
> @EricPHassey My solution is to correct the wrong way.
> 
> ```
>  @override
>  void addAllowedPointer(PointerDownEvent event) {
>    if (ready) {
>      ready = false;
>      _pointerLocations = <int, Offset>{};
>    }
>    super.addAllowedPointer(event);
>  }
> ```

This worked for me as well with android, but not IOS. (maybe someone can confirm it's not just me, and I'd be super happy)

**Comment by renancaraujo** [comment]
Should be included on 0.12.0. Further discussion on this use #441
