### ISSUE TITLE
How can I use an Image object from dart:io  instead of image provider to display image ?

### ISSUE THREAD

**Issue by radha1990kumari** [fireslime/photo_view#437]
I am using ImagePicker package to get image and then using `readasbytes` to convert it into Uint8list  then using `decodeImageFromList` function of dart:io to get image object ,now how can I display this .

**Comment by FaKenKoala** [comment]
You can get file from ImagePicker.
```
PickedFile? pickedFile = await ImagePicker().getImage(source: ImageSource.gallery);
if (pickedFile != null) {
   File file = File(pickedFile.path);
}
```

Then use FileImage ImageProvider.
```
PhotoView(
	imageProvider: FileImage(file),
)
```

**Comment by radha1990kumari** [comment]
@FaKenKoala  thnx will try that.
