### ISSUE TITLE
[BUG] GestureDetector only works in the center

### ISSUE THREAD

**Issue by florianthiel** [fireslime/photo_view#438]
**Describe the bug**
If using PhotoView.customChild with a custom GestureDetector the GestureDetector only works in the center of the child. Gestures on the top and bottom aren't recognized.

**To Reproduce**
```
PhotoView.customChild(
  disableGestures: true,
  minScale: PhotoViewComputedScale.contained,
  maxScale: PhotoViewComputedScale.covered*2,
  childSize: analyse.size,
  child: GestureDetector(
    onPanStart: (DragStartDetails start) {
      setState(() {
        _opacity = 0;
        history.add(start.localPosition, analyse.id);
      });
    },
    onPanUpdate: (DragUpdateDetails update) {
      setState(() {
        history.updateCurrent(update.localPosition, analyse.id);
      });
    },
    onPanEnd: (DragEndDetails end) {
      setState(() {
        _opacity = 1;
        history.endCurrent();
      });
      BlocProvider.of<TrainingRoomBloc>(c).add(AddPaint(history.lastPaint, analyse.id));
    },
    child: Image(image: ExImage.paint(analyse.id),)
  )
),
```

**What is the current behavior?**
Custom GestureDetector not working across the whole child.

**Expected behavior**
Custom GestureDetector should work across the whole child.

**Screenshots**
GestureDetector only works in the yellow marked area. But it should work across the whole image
![IMG_4E51FF918C44-1](https://user-images.githubusercontent.com/25753011/124393960-6f797700-dcfd-11eb-8cb9-5696b0aea22a.jpeg)

photo_view: ^0.11.1
flutter: 2.2.3

**Comment by renancaraujo** [comment]
Hello @florianthiel. 

This may be related to https://github.com/fireslime/photo_view/issues/88 where there is a framework issue with hit-testing under transformed widgets.
Everything under custom child is transformed. With means that the gesture detector will only affect the initially visible part of the image when scale is 1. Is there a way yu could wrap photo view entirely with the gesture detector?

**Comment by florianthiel** [comment]
You are right. This is actually a framework issue. The part of the customChild which would normally be out of the screen bounds isn't able to receive any GestureDector events. I fixed this issue by setting the size of the customChild to fit into the screen bounds. Now the whole child is able to receive GestureDector events.
